language: rust
sudo: false

cache:
  - cargo

branches:
  only:
    - staging
    - trying
    - master

rust:
  - nightly

script:
  - cargo build --features="unsafe_docs_rs_mmio_listing_override"
  - cargo test --features="unsafe_docs_rs_mmio_listing_override"
